#!/usr/bin/env bash
set -e


echo "Setting permissions for the docker container..."
/usr/local/dev/map_user || true
chown -R $DOCKER_USER:$DOCKER_GROUP /var/www || true
echo "Done."

apachectl -DFOREGROUND
